blank_issues_enabled: false
contact_links:
  - name: AWS Mirrorbot Channels
    url: https://t.me/awsmirror
    about: Daily Updates Channels
  - name: AWS MIRROR ZONE Group
    url: https://t.me/awsmirrorzone
    about: Mirror to AWS MIRROR ZONE Group
  - name: AWS Chat Group
    url: https://t.me/aws_public_chat
    about: Support Group
